- hosts: localhost
  connection: local

  vars:
    homebrew_packages:
      - name: awscli
      - name: go
      - name: python3
      - name: mas
      - name: node
      - name: fish

    homebrew_cask_packages:
      - name: alfred
      - name: bartender
      - name: sourcetree
      - name: iterm2
      - name: google-japanese-ime
      - name: visual-studio-code
      - name: 1password
      - name: dropbox
      - name: appium
      - name: java
      - name: android-studio

  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes

    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'

    - name: homebrew cask packages install
      homebrew_cask: name={{ item.name }} state=installed
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'
